name: betfairArb
channels:
- anaconda-fusion
- defaults
dependencies:
- pip=9.0.1=py36_1
- python=3.6.1=2
- setuptools=27.2.0=py36_1
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py36_0
- pip:
  - betfair.py==0.2.2
  - cassandra-driver==3.10
  - configparser==3.5.0
  - decorator==4.0.11
  - enum34==1.1.6
  - inflection==0.3.1
  - invoke==0.17.0
  - mysqlclient==1.3.10
  - numpy==1.12.1
  - pandas==0.20.1
  - python-dateutil==2.6.0
  - pytz==2017.2
  - requests==2.14.2
  - schematics==1.1.1
  - six==1.10.0
  - sqlalchemy==1.1.10
  - structlog==17.2.0
  - install/mysqlclient-1.3.10-cp36-cp36m-win_amd64.whl