list_match = [
"Veracruz v Queretaro",
"Tigres v Pumas UNAM",
"Alebrijes de Oaxaca v Dorados",
"Montreal Impact v Real Salt Lake",
"New York Cosmos v Indy Eleven",
"Orlando City v Columbus",
"Colo Colo v Univ de Concepcion",
"Richmond Kickers v Toronto FC II (USL)",
"Sporting San Miguelito v Tauro FC",
"Santa Fe v Deportivo Cali",
"Bucaramanga v Patriotas",
"Lobos BUAP v CF America",
"Libertad v General Diaz",
"Taubate v Santos FC B",
"Paysandu v Parana",
"Linense SP v Ferroviaria",
"Flamengo v Atletico GO",
"Aguila v FAS",
"The Strongest v Club Petrolero",
"Antofagasta v Palestino",
"Barnechea v Deportes Copiapo",
"CSYD Mixco v Deportivo Carcha",
"Cucuta Deportivo v Fortaleza (Col)",
"Sevilla v Espanyol",
"Rionegro v Tigres (Col)",
"Caracas v Zulia",
"Valladolid v Barcelona B",
"San Fernando CD v Villanovense",
"Guarani SP v Santa Cruz PE",
"Deportivo JBL Zulia v Atletico Socopo",
"Floresta EC B v Itapipoca EC B",
"FC Cartagena v Recreativo Huelva",
"Corinthians v Vitoria BA",
"Rijeka v Lokomotiva",
"Noroeste Bauru v Penapolense",
"Extremadura UD v Cordoba B",
"Jorge Wilstermann v Nacional Potosi",
"Real Madrid Castilla v CF Rayo Majadahonda",
"Bragantino SP v Tombense",
"Magallanes v Puerto Montt",
"Confianca v CSA",
"Tupi v Mogi Mirim",
"Adana Demirspor v Rizespor",
"Verona v Napoli",
"Osmanlispor v Galatasaray",
"Heerenveen v Heracles",
"Racing Club (Uru) v Cerro",
"Nacional (Uru) v Juventud (Uru)",
"Union Espanola v San Luis (Chile)",
"Hercules v Olot",
"Avellino v Frosinone",
"Oud-Heverlee Leuven v Cercle Brugge",
"KV Mechelen v Antwerp",
"Boston River v Plaza Colonia",
"Ujpest v Diosgyori",
"Jagiellonia Bialystock v Slask Wroclaw",
"Longford v Athlone",
"Numancia v Huesca",
"NK Maribor v Krsko",
"Girona v Atletico Madrid",
"Olaria v Sao Goncalo EC RJ",
"Sarajevo v Zeljeznicar",
"Eupen v Oostende",
"Eupen v Oostende",
"Montpellier v Strasbourg",
"Mlada Boleslav v Slovan Liberec",
"Sao Jose dos C EC (W) v Audax Sao Paulo (W)",
"Cukaricki v Radnicki Nis",
"CSKA Sofia v Vitosha Bistritsa",
"Nice v Guingamp",
"Waasland-Beveren v Lokeren",
"Marbella v Merida AD",
"Cruzeiro RS v Esporte Clube Igrejinha",
"Waasland-Beveren v Lokeren",
"Rennes v Dijon",
"St Etienne v Amiens",
"ESTAC Troyes v Nantes",
"Javor v Vojvodina",
"Marilia AC U20 v Olimpia FC U20",
"AZ Alkmaar v ADO Den Haag",
"Hapoel Beer Sheva v Maccabi Netanya",
"Limerick v Bohemians",
"Atarfe Industrial CF v Real Jaen",
"Torpedo Kutaisi v Dila Gori",
"Zlate Moravce v Tatran Presov",
"Wals-Grunau v Pinzgau Saalfelden",
"Giresunspor v Adanaspor",
"Atletico Baleares v Villarreal B",
"Osasuna v Sevilla B",
"Alcorcon v Sporting Gijon",
"Rubin Kazan v Anzhi Makhachkala",
"Club Atletico Saguntino v CD Ebro",
"FK Spartak v Vozdovac",
"ROW Rybnik v Wisla Pulawy",
"Thun v Lausanne",
"Obolon-Brovar v MFC Mykolaiv",
"UE Vilassar de Mar v AE Prat",
"FK Senica v FC Nitra",
"Rapperswil-Jona v Wohlen",
"Valladolid B v AD Union Adarve",
"FC Vilafranca v LHospitalet",
"Sliema Wanderers v Senglea Athletic FC",
"Trencin v Zemplin",
"GKS Belchatow v Siarka Tarnobrzeg",
"Chiasso v FC Wil",
"Bursaspor v Alanyaspor",
"Spartak Trnava v Slovan Bratislava",
"Schalke v RB Leipzig",
"Twente v VVV",
"Shakhtar v Olimpik Donetsk",
"Sunderland v Leeds",
"Stoke City v Arsenal",
"Wolfsberger AC v Admira Wacker",
"Balzan v Naxxar Lions FC",
"Celta Vigo v Sociedad",
"Xanthi v Lamia",
"Hapoel Haifa v Hapoel Ashkelon",
"Asteras Tripolis v PAS Giannina",
"CD Cova Piedade U19 v Setubal U19",
"FC Armavir v Afips",
"Karabukspor v Basaksehir",
"CD Vitoria v Tudelano",
"Genk v Charleroi",
"Lillestrom v Valerenga",
"Amorebieta v Lealtad",
"Puskas Akademia v Balmazujvarosi",
"Juventus v Cagliari",
"Qarabag FK v Inter Baku",
"Mezokovesd-Zsory v Honved",
"Torpedo BelAZ v Vitebsk",
"Degerfors v Varbergs BoIS",
"Bohemians 1905 v Slavia Prague",
"UD Las Zocas v UD Las Palmas III",
"Piast Gliwice v Korona Kielce",
"Hapoel Raanana v Hapoel Kiryat Shmona",
"Llagostera v Alcoyano",
"FC Copenhagen v SonderjyskE",
"Opava v Banik Sokolov",
"CCD Cerceda v CDA Navalcarnero",
"Tammeka Tartu v Trans Narva",
"FCI Tallinn II v Tallinna Kalev",
"Gaz Metan Medias v ACS Poli Timisoara",
"Stade Gabesien v Olympique de Medenine",
"Vereya v Lokomotiv Plovdiv",
"Tondela v Estoril Praia",
"Kremin v Inhulets Petrove",
"Gorodeya v Slutsk",
"Academico de Viseu v Leixoes",
"FC Ashdod v Maccabi Petach Tikva",
"Kremin v Inhulets Petrove",
"Santiago Wanderers v Univ Catolica (Chile)",
"Banik Ostrava v Teplice",
"Zlin v MFK Karvina",
"Puszcza Niepolomice v Odra Opole",
"Olimpia Grudziadz v Chrobry Glogow",
"Union St Gilloise v Westerlo",
"MAS Taborsko v Pribram",
"MAS Taborsko v Pribram",
"Oliveirense v Nacional",
"Cova da Piedade v Arouca",
"Uniao Madeira v Academica",
"Covilha v Guimaraes B",
"Gandzasar Kapan v FC Shirak",
"Volgar Astrakhan v FK Avangard Kursk",
"Macva Sabac v Rad",
"Varzim v Gil Vicente",
"Lyon v Bordeaux",
"Porto B v Penafiel",
"Camacha v Sanjoanense",
"Spartak Moscow v Lokomotiv",
"Aston Villa v Norwich",
"Aberdeen v Dundee",
"Rangers v Hearts",
"Aberdeen v Dundee",
"Motherwell v Ross Co",
"Raith v Forfar",
"Alloa v Queens Park",
"Bristol City v Millwall",
"Stranraer v Ayr",
"Zhemchuzhyna Odesa v Hirnyk-Sport",
"Montrose v Cowdenbeath",
"Stirling v Edinburgh City",
"Zhemchuzhyna Odesa v Hirnyk-Sport",
"Stevenage v Grimsby",
"Accrington v Mansfield",
"Crewe v Barnet",
"Chesterfield v Port Vale",
"Luton v Colchester",
"Crawley Town v Cambridge Utd",
"Morecambe v Swindon",
"Coventry v Newport County",
"Exeter v Lincoln",
"Forest Green v Yeovil",
"Honka v Haka",
"Rapid Vienna v Sturm Graz",
"Bolton v Derby",
"BK-46 v FC Espoo",
"TPV v KaPa",
"MuSa v Tampere Utd",
"Liverpool v C Palace",
"Elgin v Clyde",
"Hibernian v Hamilton",
"St Johnstone v Partick",
"HIFK v RoPS",
"PS Kemi v FC Inter",
"Wycombe v Notts Co",
"Fulham v Sheff Wed",
"Bury v Bristol Rovers",
"Nottm Forest v Middlesbrough",
"MK Dons v Gillingham",
"Portsmouth v Walsall",
"Shrewsbury v Rochdale",
"Inverness CT v Morton",
"Southampton v West Ham",
"Fleetwood Town v AFC Wimbledon",
"Queen of South v Dumbarton",
"Dundee Utd v Brechin",
"Livingston v St Mirren",
"Doncaster v Blackpool",
"Dunfermline v Falkirk",
"Ipswich v Brentford",
"Preston v Reading",
"QPR v Hull",
"Wolves v Cardiff",
"Syrianska FC v Osters",
"Scunthorpe v Oxford Utd",
"Triglav v Gorica",
"Southend v Plymouth",
"Oldham v Wigan",
"Burnley v West Brom",
"Bournemouth v Watford",
"Bradford v Blackburn",
"Peterborough v Rotherham",
"Mainz v Hannover",
"Wolfsburg v Dortmund",
"Hertha Berlin v Stuttgart",
"Hamburg v Augsburg",
"Hoffenheim v Werder Bremen",
"Arka Gdynia v Pogon Szczecin",
"Bronshoj v Skovshoved",
"FC Orenburg v Luch-Energiya",
"FC Khimki v Shinnik",
"Aarhus Fremad v FC Sydvest",
"Odder v Jammerbught FC",
"Ranheim v Levanger",
"Lens v Brest",
"Dinamo Moscow (Y) v FC Ufa (Y)",
"Frem v Naestved",
"AB v Hillerod Fodbold",
"Red Star v Marseille Consolat",
"Chemnitzer v Osnabruck",
"Preussen Munster v FC Magdeburg",
"Werder Bremen II v Wehen Wiesbaden",
"Dalum v Greve",
"Hallescher FC v Unterhaching",
"Dinamo St Petersburg v Tomsk",
"Ural v CSKA Moscow",
"Rot-Weiss Erfurt v Paderborn",
"SG Sonnenhof v Aalen",
"Tyumen v Kryliya Sovetov",
"Kjellerup v IF Lyseng",
"Hebei CFFC v Beijing Guoan",
"Shanghai Shenhua v Guangzhou FC",
"Liaoning Whowin v Tianjin Elion",
"Swansea v Man Utd",
"Kilmarnock v Celtic",
"Albirex Niigata v Tampines Rovers",
"Sheff Utd v Barnsley",
"VSK Aarhus (W) v Brondby (W)",
"HIK v Naesby",
"Fortuna Dusseldorf v Kaiserslautern",
"FC Heidenheim v Duisburg",
"Randers Freja U19 v FC Midtjylland U19",
"Aalborg BK U19 v Esbjerg fB U19",
"Urawa v FC Tokyo",
"Dynamo Dresden v SV Sandhausen",
"Meghalaya v Langsning SC",
"Famalicao v Benfica B",
"Sibir v FC Olimpiyets NN",
"Yenisey Krasnoyarsk v Zenit St Petersburg II",
"Sibir v FC Olimpiyets NN",
"Wolfsburg II v Lubeck",
"Guizhou HF Zhicheng v Shanghai East Asia",
"FC Hradec Kralove U19 v FC Banik Ostrava U19",
"Potsdam (W) v Paris St-G (W)",
"G-Osaka v Kashiwa",
"FC Hradec Kralove U19 v FC Banik Ostrava U19",
"FC Seoul v Ulsan Hyundai Horang-i",
"Vejle BK U19 v OB Odense U19",
"Tosu v Omiya",
"Braga B v Santa Clara",
"Niigata v Sendai",
"Kawasaki v Sapporo",
"Hiroshima v Kofu",
"Braga B v Santa Clara",
"Yokohama SCC v Tochigi SC",
"LDU Loja v Imbabura SC",
"LDU Loja v Imbabura SC",
"Goias v America MG",
"Racing Club v Atletico Mitre",
"Sao Bento v Joinville",
"Criciuma v Oeste",
"Nacional (Par) v Sportivo Luqueno",
"Audax Italiano v Deportes Temuco",
"Juventude v Vila Nova",
"Valencia v Las Palmas",
"Tenerife v Zaragoza",
"Rio Ave v Portimonense",
"Throttur v HK Kopavogur",
"Wexford v Cabinteely",
"Galway Utd v Shamrock Rovers",
"Burton v Birmingham",
"Kasimpasa v Besiktas",
"Metz v Monaco",
"Tarxien Rainbows FC v Hamrun Spartans FC",
"St Patricks v Finn Harps",
"Shelbourne v Cobh Ramblers",
"Waterford v UCD",
"Bray v Drogheda",
"Gornik Leczna v Stal Mielec",
"Manisaspor v Samsunspor",
"Bayern Munich v Leverkusen",
"Cork City v Sligo Rovers",
"Lierse v Roeselare",
"Parma v Empoli",
"Standard v Zulte-Waregem",
"FC Wacker Innsbruck v FC Liefering",
"Sparta Prague v Slovacko",
"Randers v Silkeborg",
"Leganes v Alaves",
"Neuchatel Xamax v Schaffhausen",
"Volendam v Helmond Sport",
"Chelsea U23 v Derby U23",
"Cambuur v Jong Ajax",
"Roda JC v Vitesse",
"Astra Giurgiu v CSMS Iasi",
"MVV Maastricht v Go Ahead Eagles",
"Chojniczanka Chojnice v Podbeskidzie B-B",
"Den Bosch v Jong AZ Alkmaar",
"Reims v Bourg-Peronnas",
"Istra v Cibalia",
"Ajaccio GFCO v US Quevilly",
"Le Havre v Valenciennes",
"Nancy v Sochaux",
"Clermont v Lorient",
"Niort v Tours",
"AC Ajaccio v Paris FC",
"Lorca FC v Leonesa",
"Auxerre v Orleans",
"NEC Nijmegen v Almere City",
"Thor v Fram",
"Hrvatski Dragovoljac v NK Dugopolje",
"FC Eindhoven v Telstar",
"Fortuna Sittard v Dordrecht",
"Everton U23 v Leicester U23",
"Thor v Fram",
"Vendee Les Herbiers v Lyon Duchere",
"Waalwijk v Emmen",
"Boulogne v Grenoble",
"Pirin Blagoevgrad v Levski Sofia",
"Wiener SK v FC Stadlau",
"Znojmo v Frydek Mistek",
"Debrecen v Vasas",
"That Ras v Al Wehdat",
"MKS Kluczbork v Olimpia Elblag",
"Fortuna Koln v Karlsruhe",
"Jonkopings Sodra v Elfsborg",
"Orgryte v IK Frej",
"Denizlispor v Istanbulspor",
"Denizlispor v Istanbulspor",
"Flora Tallinn v Paide Linnameeskond",
"Tosno v SKA-Khabarovsk",
"Hvidovre v B93",
"SV Darmstadt v St Pauli",
"Braunschweig v Erzgebirge",
"SC Wiener Neustadt v WSG Wattens",
"Hartberg v SV Ried",
"FAC Wien v KSV 1919",
"Austria Lustenau v BW Linz",
"Marienlyst v Kolding IF",
"FAC Wien v KSV 1919",
"Birkirkara v Floriana",
"Lija Athletic FC v Gzira United FC",
"Podbrezova v Ruzomberok",
"FC Kiffen v JaPS",
"Lechia Gdansk v Sandecja Nowy Sacz",
"CS Mioveni v Olimpia Satu Mare",
"FK Energomash Belgorod v Ararat Moscow",
"AC Horsens v AaB",
"Gomel v Isloch",
"FCI Tallinn v Tulevik Viljandi",
"Sillamae Kalev v Nomme Kalju",
"Botev Plovdiv v Cherno More",
"OPS v Jaro",
"EsPa v FC Viikingit",
"FK Pskov 747 v FK Dolgoprudny",
"NuPS v FC Jazz",
"Kamaz v Neftekhimik",
"Tekstilshchik v CRFSO Smolensk",
"Naftan v Dnepr Mogilev",
"HNK Gorica (Croatia) v GNK Dinamo Zagreb II",
"Club Leon FC (Premier) v Loros U de C (Premier)",
"Sokol v Zorkiy Krasnogorsk",
"Rubin Kazan (Y) v Anzhi (Y)",
"Mordovia Saransk v FK Lada Tolyatti",
"Al Ahli (JOR) v Al Ramtha",
"FK Chertanovo v FK Lokomotiv-Kazanka",
"Monarcas Morelia U20 v Pachuca U20",
"Torpedo Vladimir v Znamya Truda",
"FK Murom v Dinamo St. P II",
"FK Biolog Novokubansk v SKA Rostov",
"FK Rotor Volgograd II v FK Torpedo Moskva",
"Spartak Moscow (Y) v Lokomotiv Moscow (Y)",
"Zenit Izhevsk v Syzran 2003",
"Metallurg Bekabad v Lokomotiv Tashkent",
"Hapoel Petach Tikva v Hapoel Katamon",
"Hapoel Nazareth Illit v Hapoel Marmorek",
"Hapoel Ramat Gan v Hapoel Kfar Saba",
"Maccabi Herzliya v Hapoel Afula",
"Hapoel Eran Hadera v Ironi Ramat HaSharon",
"Birmingham U23 v Coventry U23",
"FK Orenburg II v Anzhi-Jnr Zelenodolsk",
"Barnsley U23 v Colchester U23",
"Dinamo Samarqand v Pakhtakor",
"FK Mlada Boleslav U19 v FC Zlin U19",
"Hougang Utd v Geylang International",
"Long An FC U21 v Can Tho FC U21",
"Long An FC U21 v Can Tho FC U21",
"TP Ho Chi Minh FC U21 v PVF U21",
"Ha Noi T&T U21 v Song Lam Nghe An U21",
"Viettel FC U21 v Thanh Hoa U21",
"Quang Nam U21 v Da Nang U21",
"Arema Cronus v Persiba Balikpapan",
"Dong Thap U21 v An Giang U21",
"Ba FC v Lautoka FC",
"Dak Lak FC U21 v Dong Nai U21",
"Alianza FC (SLV) v CD Olimpia",
"Gremio U20 v Atletico PR U20",
"Cruzeiro U20 v Sao Paulo U20",
"Operario PR U23 v AC Paranavai U23",
"Once Caldas v Tolima",
"Botafogo RJ U20 v Coritiba U20",
"Atletico Huila v Junior",
"Maritimo v Dynamo Kiev",
"Stjarnan (W) v Valur (W)",
"Everton v Hajduk Split",
"Partizan Belgrade v Videoton",
"AC Milan v Shkendija",
"Legia Warsaw v Sheriff Tiraspol",
"Club Brugge v AEK Athens",
"Ajax v Rosenborg",
"Osijek v Austria Vienna",
"Ludogorets v FK Suduva",
"SCR Altach v Maccabi Tel Aviv",
"Panathinaikos v Athletic Bilbao",
"Plzen v AEK Larnaca",
"Germany U19 (W) v France U19 (W)",
"PAOK v Ostersunds FK",
"Vardar Skopje v Fenerbahce",
"Hafnarfjordur v Braga",
"LSK Kvinner (W) v Avaldsnes (W)",
"AS Eupen (Res) v Anderlecht (Y)",
"Apollon Limassol v FC Midtjylland",
"Dinamo Zagreb v Skenderbeu",
"Ullensaker Kisa v Start",
"1860 Munich v Illertissen",
"FK Krasnodar v Crvena Zvezda",
"EIF Ekenas II v MPS Helsinki",
"BATE Borisov v Oleksandria",
"Rakvere Tarvas v Tartu Santos",
"Ferencvaros v Haladas",
"Spartaks Jurmala v FS METTA LU",
"PK-37 v SC KuFu-98",
"Al Jazeera (JOR) v Mansheyat",
"Al Yarmouk Amman v Al Hussein",
"Kauno Zalgiris v FC Stumbras",
"Netherlands U19 (W) v Spain U19 (W)",
"Balestier Khalsa v Warriors FC",
"Mohammedan SC v Tollygunge Agragami",
"Boys Sports Company v Shillong Lajong",
"FK Ural II v Volga Ulyanovsk",
"Tosno U21 v SKA-Khabarovsk (Y)",
"Aguila v Arabe Unido",
"UAEM Potros v CF America",
"Atletico Nacional (Col) v America de Cali",
"Deportivo Cali v Ind Medellin",
"Botafogo RJ v Flamengo",
"Gremio v Cruzeiro",
"Lanus v Union Santa Fe",
"Chicago Red Stars (W) v Seattle Reign FC (W)",
"Leon v Veracruz",
"Necaxa v Mineros de Zacatecas",
"Dorados v Toluca",
"Montreal Impact v Chicago Fire",
"Deportivo Tachira v Trujillanos",
"Orlando City U23 v Ottawa Fury",
"Caracas v Metropolitanos",
"Estudiantes de Merida v Zamora",
"Patriotas v Santa Fe",
"Penapolense v Ferroviaria",
"Guarani SC v Camboriu",
"Fluminense RJ U20 v Chapecoense U20",
"Atletico Venezuela v Deportivo La Guaira",
"Cortulua v Rionegro",
"Alianza Petrolera v Deportivo Pasto",
"Alianza Petrolera v Deportivo Pasto",
"Real Madrid v Barcelona",
"Portuguesa (Ven) v Deportivo Lara",
"Deportes Recoleta v Independiente Cauquenes",
"KR Reykjavik (W) v Hafnarfjordur (W)",
"Atletico Socopo v Carabobo FC",
"Tigres (Col) v Bucaramanga",
"Slimbridge AFC v Cirencester",
"Basaksehir v Sevilla",
"Napoli v Nice",
"Olympiakos v Rijeka",
"Celtic v FC Astana",
"Hapoel Beer Sheva v NK Maribor",
"E Stirling v Ayr",
"Sheff Wed v Sunderland",
"Norwich v QPR",
"Portsmouth v Fulham U21",
"CP Villarrobledo v Albacete",
"Barra FC (Camboriu) v Hercilio Luz FC",
"Dundee U20 v Alloa",
"Iraty SC U23 v Assoc Portuguesa U23",
"Barra FC (Camboriu) v Hercilio Luz FC",
"Fluminense (Joinville) v Marcilio Dias",
"Motherwell U20 v Queens Park",
"ADI Union Rosario v CA San Jorge",
"Serrano FC (RJ) v Serra Macaense FC",
"IBV v Vikingur Olafsvik",
"Barra da Tijuca FC v Queimados FC",
"Sao Cristovao v Barcelona Esporte Clube",
"CS Sfaxien v Monastir",
"SSV Jeddeloh v Germania E-L",
"Koniz v Bavois",
"Lubeck v Weiche Flensburg",
"SV Rochling Volklingen v Waldhof Mannheim",
"FC Koln U19 v Arm Klosterhardt U19",
"Asane v Kongsvinger",
"Zalgiris v Jonava",
"Strommen v Ranheim",
"Hamburger SV U19 v Wolfsburg U19",
"Lugano v St Gallen",
"Leverkusen U19 v Arminia Bielefeld U19",
"Bayern Munich U19 v Karlsruher SC U19",
"Flora Tallinn II v Tallinna Kalev",
"FC Maardu v Levadia Tallinn II",
"Utrecht v Zenit St Petersburg",
"Fortuna Dusseldorf U19 v SC Fortuna Koln U19",
"VfL Bochum U19 v Oberhausen U19",
"Hertha BSC Berlin U19 v RB Leipzig U19",
"MP v Klubi-04",
"Ben Guerdane v Zarzis",
"TJ Kovo Belusa v Zlate Moravce",
"FK Karosta v RFS",
"Eding Sport de Lekie v Cotonsport de Garoua",
"Racing de Bafoussam v Young Sports Academy",
"1. FC Magdeburg U19 v 1. FSV Mainz 05 U19",
"FK Ventspils v FK Liepaja",
"NK Ilirija 1911 v Krsko",
"NK Tabor Sezana v Rudar",
"Vasco da Gama U20 v CR Flamengo U20",
"Feutcheu FC v Colombe du Dja et Lobo",
"Canon Yaounde v UMS de Loum",
"1. FC Union Berlin U19 v FC St. Pauli U19",
"FK Irtysh Omsk v Smena Komsomolsk",
"FK Irtysh Omsk v Smena Komsomolsk",
"Persebaya Surabaya v PSIM Yogyakarta",
"Dinamo Barnaul v FC Sakhalin",
"Home Utd v Brunei DPMM FC",
"Da Nang U21 v Hue U21",
"An Giang U21 v Long An FC U21",
"Okayama v Ehime",
"Mito v Kyoto",
"Jef Utd Chiba v Shonan",
"Hannover 96 U19 v Chemnitzer FC U19",
"FC Machida v Nagoya",
"Schalke U19 v E Braunschweig U19",
"Ceske Budejovice U19 v Sparta Prague U19",
"1. FC Nurnberg U19 v SC Freiburg U19",
"SG Dynamo Dresden U19 v SV Werder Bremen U19",
"Quang Nam U21 v Khanh Hoa U21",
"PVF U21 v Dak Lak FC U21",
"Dong Thap U21 v Tien Giang FC U21",
"Dong Nai U21 v Binh Phuoc U21",
"Orange County Blues v Tulsa Roughnecks FC",
"Chorrillo v Santos de Guapiles",
"Cruz Azul v Zacatepec",
"Envigado v La Equidad",
"Nautico v Figueirense",
"River Plate v CA Atlas",
"Queretaro v Pachuca",
"Celaya v Monterrey",
"Puebla v Tijuana",
"Londrina v Brasil de Pelotas",
"San Lorenzo v Cipolletti",
"CSD San Antonio Unido v Club Malleco Unido",
"Buckie Thistle v Brechin",
"Reading v Aston Villa",
"Palestino v Colo Colo",
"Leeds v Fulham",
"Wrexham v Gateshead",
"Limerick v Shamrock Rovers",
"Young Boys v CSKA Moscow",
"Glentoran v Dungannon Swifts",
"Cheltenham v Swansea U21",
"Luton v Tottenham U21",
"Swindon v West Ham U21",
"Notts Co v Everton U21",
"Kilmarnock U20 v Berwick",
"Middlesbrough v Burton",
"Carrick Rangers v Ballymena",
"Dundee Utd v Cowdenbeath",
"Carrick Rangers v Ballymena",
"Morton v Livingston",
"Albion v Spartans",
"Coleraine v Cliftonville",
"Crusaders v Warrenpoint Town",
"Dag and Red v Ebbsfleet Utd",
"St Mirren v East Kilbride",
"Raith v Brora Rangers",
"Brentford v Bristol City",
"FC Halifax Town v Dover",
"Dunfermline v Arbroath",
"Guiseley v Tranmere",
"Queen of South v Airdrieonians",
"AFC Fylde v Maidenhead",
"Maidstone Utd v Aldershot",
"Stirling v Montrose",
"Hoffenheim v Liverpool",
"Hibernian U20 v Elgin",
"Birmingham v Bolton",
"Solihull Moors v Barrow",
"Sligo Rovers v Bray",
"Hull v Wolves",
"Derby v Preston",
"Sporting Lisbon v FCSB",
"Cardiff v Sheff Utd",
"Ross Co U20 v Forfar",
"Goncalense FC v Americano",
"Al Ahly v Al Masry",
"Rotherham v Man City U21",
"Plymouth v Chelsea U21",
"Mannsdorf v Rapid Vienna (Am)",
"Bani Yas v Bengaluru",
"Austria Vienna (Am) v Wiener SK",
"FCM TQS Traiskirchen v First Vienna",
"Trelleborgs v Norrby IF",
"Degerfors v Falkenbergs",
"Tammeka Tartu v Levadia Tallinn",
"KSV 1919 v SC Wiener Neustadt",
"FC Liefering v FAC Wien",
"WSG Wattens v Austria Lustenau",
"BW Linz v Hartberg",
"SC Spelle Venhaus v Drochtersen-Assel",
"Mortagua v Tondela",
"SC Schwaz v Wals-Grunau",
"Qarabag FK v FC Copenhagen",
"Girona v Man City",
"1. FC Heidenheim U19 v TSG Hoffenheim U19",
"Trans Narva v FCI Tallinn",
"Parnu JK Vaprus v Nomme Kalju",
"FC Stadlau v SV Schwechat",
"Stade Gabesien v Kairouan",
"KS Sola Oswiecim v KS Chelmianka Chelm",
"Malmin Ponnistajat v HooGee",
"LKS Wislanie Jaskowice v SKS Wisla Sandomierz",
"Sillamae Kalev v Flora Tallinn",
"Prostejov v Opava",
"AS Fortuna Mfou v National Polytechnic FC",
"Ismaning v TuS Holzkirchen",
"Slask Wroclaw v Nieciecza",
"Garching v Bayern Munich II",
"Geylang Utd (Res) v Balestier Khalsa (Res)",
"MKS Trzebinia Siersza v LKS Wolczanka WP",
"Urawa v Chapecoense",
"Unterfohring v Pipinsried",
"FK Teplice U19 v SK Slavia Praha U19",
"SV Worgl v Wacker Innsbruck (Am)",
"Quindio v Boyaca Chico",
"Emelec v Fuerza Amarilla",
"Boca Juniors v Gimnasia y Tiro (Salta)",
"Operario PR v Maranhao",
"Nacional (Uru) v Penarol",
"Cerro Porteno v Libertad",
"Cerro Porteno v Libertad",
"Santos v Fluminense"
]